name: robosuite_two_arm_lift

task_name: TwoArmLift

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim, point_cloud
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [24]  # robot0_joint_pos(6) + robot0_gripper_qpos(6) + robot1_joint_pos(6) + robot1_gripper_qpos(6)
      type: low_dim
  action:
    shape: [14]    # robot0_joint_delta(6) + robot0_gripper(1) + robot1_joint_delta(6) + robot1_gripper(1)

env_runner:
  _target_: diffusion_policy_3d.env_runner.robosuite_two_arm_lift_runner.RobosuiteTwoArmLiftRunner
  n_train: 20
  max_steps: 400
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 20
  task_name: TwoArmLift

dataset:
  _target_: diffusion_policy_3d.dataset.robosuite_dataset.RobosuiteDataset
  zarr_path: /home/rosi/3D-Diffusion-Policy/3D-Diffusion-Policy/data/two_arm_lift_demo.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.05
  max_train_episodes: null
